# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc "A simple CLI for currency conversion"
  homepage "https://github.com/PriyabrataMo/currency"
  version "0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PriyabrataMo/currency/releases/download/v0.2/currency_0.2_darwin_amd64.tar.gz"
      sha256 "b09de00be79ec8cc9db798da1916b5454a44e00dbcca3f8ced7fd7e68ab2493e"

      def install
        bin.install "currency"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PriyabrataMo/currency/releases/download/v0.2/currency_0.2_darwin_arm64.tar.gz"
      sha256 "1f9f5ec4a8af7681ad0c39f084374a5deffda4b52a2f2626b1de763110846456"

      def install
        bin.install "currency"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PriyabrataMo/currency/releases/download/v0.2/currency_0.2_linux_amd64.tar.gz"
        sha256 "19f27f38c34a372d2a275afb3693544f3df4537436e957c97516ef429e493266"

        def install
          bin.install "currency"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PriyabrataMo/currency/releases/download/v0.2/currency_0.2_linux_arm64.tar.gz"
        sha256 "a58986baf9e441edd6453d19e58310411ac9ce4042ff7a25b1edb7fc50955c91"

        def install
          bin.install "currency"
        end
      end
    end
  end
end
